# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-12 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_duration',
            field=models.CharField(default=datetime.datetime(2018, 8, 12, 19, 15, 45, 38846, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
